In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\heroj\anaconda3\envs\proyecto_python1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [4]:
df.index.dtype

dtype('int64')

In [5]:
df_ch = df[df['job_country'] == 'Chile']

In [ ]:
df_ch

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
91,Data Scientist,Data Scientist,"Temuco, Chile",via BeBee Chile,Full-time,False,Chile,2023-01-06 14:07:40,False,False,Chile,NaN,NaN,NaN,Talently,"['sql', 'python', 'tensorflow', 'numpy', 'pand...","{'analyst_tools': ['excel', 'tableau'], 'libra..."
133,Senior Data Scientist,Data Scientist Senior,"Santiago, Chile",via Chiletrabajos,Full-time,False,Chile,2023-07-06 13:28:33,False,False,Chile,NaN,NaN,NaN,Alaya Digital Solutions,"['python', 'sql', 'matlab', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'programming': ['p..."
237,Data Scientist,Data Science Specialist,"Santiago, Chile",via Trabajo.org,Full-time,False,Chile,2023-01-29 13:25:16,False,False,Chile,NaN,NaN,NaN,BairesDev,NaN,NaN
301,Data Scientist,Data Scientist,"Santiago, Chile",via LinkedIn,Full-time,False,Chile,2023-05-17 13:33:57,False,False,Chile,NaN,NaN,NaN,"SMU S.A. (Unimarc, M10, Alvi, y Super10)",NaN,NaN
304,Data Engineer,Principal Data Engineer,"Santiago, Chile",via BeBee Chile,Full-time,False,Chile,2023-03-11 13:26:39,False,False,Chile,NaN,NaN,NaN,McKinsey & Company,"['python', 'sql', 'scala', 'java', 'databricks...","{'cloud': ['databricks', 'aws', 'gcp', 'azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785621,Data Engineer,Data Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-09-24 06:31:57,True,False,Chile,NaN,NaN,NaN,Elite Recruitment Group,"['php', 'python', 'sql', 'aws', 'airflow', 'ha...","{'cloud': ['aws'], 'libraries': ['airflow', 'h..."
785637,Data Engineer,Data Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:31:57,True,False,Chile,NaN,NaN,NaN,Tribal Credit,"['python', 'scala', 'mysql', 'snowflake', 'ora...","{'cloud': ['snowflake', 'oracle', 'aws', 'azur..."
785644,Data Analyst,Data Analyst,"Las Condes, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-20 06:29:50,True,False,Chile,NaN,NaN,NaN,Worldgroup Careers MWT,"['sql', 'python', 'r', 'snowflake', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['sno..."
785698,Data Engineer,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:32:00,True,False,Chile,NaN,NaN,NaN,Falabella Retail,"['sql', 'python', 'gcp', 'aws', 'git']","{'cloud': ['gcp', 'aws'], 'other': ['git'], 'p..."
785701,Data Engineer,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:31:57,True,False,Chile,NaN,NaN,NaN,Falabella Retail,"['sql', 'python', 'gcp', 'aws', 'git']","{'cloud': ['gcp', 'aws'], 'other': ['git'], 'p..."

In [ ]:
#Reseteo y orden numerico con un indice creado

df_ch.reset_index(inplace=True)

In [8]:
df_ch

,index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,91,Data Scientist,Data Scientist,"Temuco, Chile",via BeBee Chile,Full-time,False,Chile,2023-01-06 14:07:40,False,False,Chile,NaN,NaN,NaN,Talently,"['sql', 'python', 'tensorflow', 'numpy', 'pand...","{'analyst_tools': ['excel', 'tableau'], 'libra..."
1,133,Senior Data Scientist,Data Scientist Senior,"Santiago, Chile",via Chiletrabajos,Full-time,False,Chile,2023-07-06 13:28:33,False,False,Chile,NaN,NaN,NaN,Alaya Digital Solutions,"['python', 'sql', 'matlab', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'programming': ['p..."
2,237,Data Scientist,Data Science Specialist,"Santiago, Chile",via Trabajo.org,Full-time,False,Chile,2023-01-29 13:25:16,False,False,Chile,NaN,NaN,NaN,BairesDev,NaN,NaN
3,301,Data Scientist,Data Scientist,"Santiago, Chile",via LinkedIn,Full-time,False,Chile,2023-05-17 13:33:57,False,False,Chile,NaN,NaN,NaN,"SMU S.A. (Unimarc, M10, Alvi, y Super10)",NaN,NaN
4,304,Data Engineer,Principal Data Engineer,"Santiago, Chile",via BeBee Chile,Full-time,False,Chile,2023-03-11 13:26:39,False,False,Chile,NaN,NaN,NaN,McKinsey & Company,"['python', 'sql', 'scala', 'java', 'databricks...","{'cloud': ['databricks', 'aws', 'gcp', 'azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8113,785621,Data Engineer,Data Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-09-24 06:31:57,True,False,Chile,NaN,NaN,NaN,Elite Recruitment Group,"['php', 'python', 'sql', 'aws', 'airflow', 'ha...","{'cloud': ['aws'], 'libraries': ['airflow', 'h..."
8114,785637,Data Engineer,Data Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:31:57,True,False,Chile,NaN,NaN,NaN,Tribal Credit,"['python', 'scala', 'mysql', 'snowflake', 'ora...","{'cloud': ['snowflake', 'oracle', 'aws', 'azur..."
8115,785644,Data Analyst,Data Analyst,"Las Condes, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-20 06:29:50,True,False,Chile,NaN,NaN,NaN,Worldgroup Careers MWT,"['sql', 'python', 'r', 'snowflake', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['sno..."
8116,785698,Data Engineer,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:32:00,True,False,Chile,NaN,NaN,NaN,Falabella Retail,"['sql', 'python', 'gcp', 'aws', 'git']","{'cloud': ['gcp', 'aws'], 'other': ['git'], 'p..."
8117,785701,Data Engineer,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:31:57,True,False,Chile,NaN,NaN,NaN,Falabella Retail,"['sql', 'python', 'gcp', 'aws', 'git']","{'cloud': ['gcp', 'aws'], 'other': ['git'], 'p..."

In [ ]:
#Ordenar por columna existente en este caso "index"
df_ch.set_index('index', inplace=True)

In [12]:
df_ch

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
index,,,,,,,,,,,,,,,,,
91,Data Scientist,Data Scientist,"Temuco, Chile",via BeBee Chile,Full-time,False,Chile,2023-01-06 14:07:40,False,False,Chile,NaN,NaN,NaN,Talently,"['sql', 'python', 'tensorflow', 'numpy', 'pand...","{'analyst_tools': ['excel', 'tableau'], 'libra..."
133,Senior Data Scientist,Data Scientist Senior,"Santiago, Chile",via Chiletrabajos,Full-time,False,Chile,2023-07-06 13:28:33,False,False,Chile,NaN,NaN,NaN,Alaya Digital Solutions,"['python', 'sql', 'matlab', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'programming': ['p..."
237,Data Scientist,Data Science Specialist,"Santiago, Chile",via Trabajo.org,Full-time,False,Chile,2023-01-29 13:25:16,False,False,Chile,NaN,NaN,NaN,BairesDev,NaN,NaN
301,Data Scientist,Data Scientist,"Santiago, Chile",via LinkedIn,Full-time,False,Chile,2023-05-17 13:33:57,False,False,Chile,NaN,NaN,NaN,"SMU S.A. (Unimarc, M10, Alvi, y Super10)",NaN,NaN
304,Data Engineer,Principal Data Engineer,"Santiago, Chile",via BeBee Chile,Full-time,False,Chile,2023-03-11 13:26:39,False,False,Chile,NaN,NaN,NaN,McKinsey & Company,"['python', 'sql', 'scala', 'java', 'databricks...","{'cloud': ['databricks', 'aws', 'gcp', 'azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785621,Data Engineer,Data Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-09-24 06:31:57,True,False,Chile,NaN,NaN,NaN,Elite Recruitment Group,"['php', 'python', 'sql', 'aws', 'airflow', 'ha...","{'cloud': ['aws'], 'libraries': ['airflow', 'h..."
785637,Data Engineer,Data Engineer,"Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:31:57,True,False,Chile,NaN,NaN,NaN,Tribal Credit,"['python', 'scala', 'mysql', 'snowflake', 'ora...","{'cloud': ['snowflake', 'oracle', 'aws', 'azur..."
785644,Data Analyst,Data Analyst,"Las Condes, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-20 06:29:50,True,False,Chile,NaN,NaN,NaN,Worldgroup Careers MWT,"['sql', 'python', 'r', 'snowflake', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['sno..."
785698,Data Engineer,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:32:00,True,False,Chile,NaN,NaN,NaN,Falabella Retail,"['sql', 'python', 'gcp', 'aws', 'git']","{'cloud': ['gcp', 'aws'], 'other': ['git'], 'p..."
785701,Data Engineer,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Chile,2023-08-09 06:31:57,True,False,Chile,NaN,NaN,NaN,Falabella Retail,"['sql', 'python', 'gcp', 'aws', 'git']","{'cloud': ['gcp', 'aws'], 'other': ['git'], 'p..."

In [13]:
median_pivot = df_ch.pivot_table(values='salary_year_avg',index='job_title_short',aggfunc=['median','min','max'])

In [15]:
median_pivot.sort_index(inplace=True)

In [16]:
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Data Analyst                     127250.0        100500.0        154000.0
Data Engineer                    146000.0         64800.0        147500.0
Data Scientist                   121000.0         64800.0        163875.0
Machine Learning Engineer        166000.0        166000.0        166000.0